apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-test
  template:
    metadata:
      labels:
        app: csi-test
    spec:
      containers:
        - name: csi-test
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: csi-test-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: csi-test-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: csi-test
  ports:
    - port: 8081
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-test-pvc
spec:
  resources:
    requests:
      storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  # storageClassName: smb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 0.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  claimRef:
    namespace: default
    name: csi-test-pvc
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: test-pv
    volumeAttributes:
      source: "//samba/sambashare"
      subDir: html
    nodeStageSecretRef:
      name: smbcreds
      namespace: default